---
- name: Copy MySQL systemd service unit
  template:
    src: mysql.service.j2
    dest: /etc/systemd/system/mysql.service
  become: yes
  notify: Restart MySQL

- name: Start MySQL service
  service:
    name: "{{ mysql_service_name }}"
    state: started
  become: yes
  
- name: Check MySQL version
  command: "{{ mysql_install_dir }}/mysql-5.7.44-linux-glibc2.12-x86_64/bin/mysql --version"
  register: mysql_version_output

- name: Display MySQL version
  debug:
    var: mysql_version_output.stdout_lines

