- name: Install MySQL dependencies on Ubuntu
  apt:
    name:
      - libaio1
      - libnuma1
    state: present
  become: yes

- name: Install libncurses5 compatibility libraries on Ubuntu 
  apt:
    name: libncurses5-compat-libs
    state: present
  become: yes

- name: Update dynamic linker cache
  command: ldconfig
  become: yes

- name: Check MySQL version
  command: "/usr/local/mysql/mysql-5.7.44-linux-glibc2.12-x86_64/bin/mysql --version"
  register: mysql_version_output

- name: Display MySQL version
  debug:
    var: mysql_version_output.stdout_lines


